[package]
name = "hila5"
version = "0.1.0"
authors = ["Sam Scott <me@samjs.co.uk>"]

[dependencies]
byteorder = "1"
digest = "0.7"
error-chain = "0.11"
lazy_static = "0.2"
ring = "0.12"
sha3  = "0.7"

[build-dependencies]
cc = "1.0"

[features]
default = ["opt"]
kat = []
opt = []
